# Generated by Django 3.0.5 on 2020-10-07 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kurslar',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi:')),
                ('img', models.ImageField(upload_to='images', verbose_name="O'qituvchi rasmi:")),
                ('about', models.TextField(verbose_name="O'qituvchi haqida:")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Category', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': "O'qituvchilar",
                'verbose_name_plural': "O'qituvchlar",
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, verbose_name='Kurs haqida')),
                ('img', models.ImageField(upload_to='images', verbose_name='Kurs uchun rasm')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Category', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Kurslar haqida',
                'verbose_name_plural': 'Kurslar haqida',
            },
        ),
    ]
